version : '3'

services:
  api-doc2:
    # image: <>
    build: .
    environment: 
      - CONF_FILE=conf.yaml
    ports :
      - "5000:5000"
    volumes: 
      - ./compose-conf.yaml:/api/conf.yaml
    restart: unless-stopped
    depends_on:
      - word-engine
      - excel-engine

  word-engine:
    image: <>
    expose: 
      - 5000
    restart: unless-stopped

  excel-engine:
    image: <>
    ports: 
      - 4000
    restart: unless-stopped

  
