version : '3'

services:
  api-doc2:
    # image: registry.dev.juniorisep.com/phoenix/api-doc2:staging
    build: .
    environment: 
      - CONF_FILE=conf.yaml
    ports :
      - "5000:5000"
    volumes: 
      - ./compose-conf.yaml:/api/conf.yaml
    restart: unless-stopped
    depends_on:
      - word-engine
      - excel-engine

  word-engine:
    image: registry.dev.juniorisep.com/phoenix/publiposting-services/word-publiposting:staging
    expose: 
      - 5000
    restart: unless-stopped

  excel-engine:
    image: registry.dev.juniorisep.com/phoenix/publiposting-services/excel-publiposting:staging
    ports: 
      - 4000
    restart: unless-stopped

  
